export const AIRPORTS_BR = [
  { name: 'Aeroporto Internacional de Guarulhos', iata: 'GRU', city: 'São Paulo', state: 'SP' },
  { name: 'Aeroporto Internacional do Galeão', iata: 'GIG', city: 'Rio de Janeiro', state: 'RJ' },
  { name: 'Aeroporto Internacional de Brasília', iata: 'BSB', city: 'Brasília', state: 'DF' },
  { name: 'Aeroporto Internacional de Viracopos', iata: 'VCP', city: 'Campinas', state: 'SP' },
  { name: 'Aeroporto Internacional de Confins', iata: 'CNF', city: 'Belo Horizonte', state: 'MG' },
  { name: 'Aeroporto Internacional Pinto Martins', iata: 'FOR', city: 'Fortaleza', state: 'CE' },
  { name: 'Aeroporto Internacional de Salvador', iata: 'SSA', city: 'Salvador', state: 'BA' },
  { name: 'Aeroporto Internacional de Recife', iata: 'REC', city: 'Recife', state: 'PE' },
  { name: 'Aeroporto Internacional de Porto Alegre', iata: 'POA', city: 'Porto Alegre', state: 'RS' },
  { name: 'Aeroporto Internacional de Curitiba', iata: 'CWB', city: 'Curitiba', state: 'PR' },
  { name: 'Aeroporto Internacional de Manaus', iata: 'MAO', city: 'Manaus', state: 'AM' },
  { name: 'Aeroporto Internacional de Belém', iata: 'BEL', city: 'Belém', state: 'PA' },
  { name: 'Aeroporto Internacional de Florianópolis', iata: 'FLN', city: 'Florianópolis', state: 'SC' },
  { name: 'Aeroporto Internacional de Goiânia', iata: 'GYN', city: 'Goiânia', state: 'GO' },
  { name: 'Aeroporto Internacional de Natal', iata: 'NAT', city: 'Natal', state: 'RN' },
  { name: 'Aeroporto Internacional de Maceió', iata: 'MCZ', city: 'Maceió', state: 'AL' },
  { name: 'Aeroporto Internacional de João Pessoa', iata: 'JPA', city: 'João Pessoa', state: 'PB' },
  { name: 'Aeroporto Internacional de São Luís', iata: 'SLZ', city: 'São Luís', state: 'MA' },
  { name: 'Aeroporto Internacional de Vitória', iata: 'VIX', city: 'Vitória', state: 'ES' },
  { name: 'Aeroporto Internacional de Cuiabá', iata: 'CGB', city: 'Cuiabá', state: 'MT' },
  { name: 'Aeroporto Internacional de Campo Grande', iata: 'CGR', city: 'Campo Grande', state: 'MS' },
  { name: 'Aeroporto Internacional de Teresina', iata: 'THE', city: 'Teresina', state: 'PI' },
  { name: 'Aeroporto Internacional de Aracaju', iata: 'AJU', city: 'Aracaju', state: 'SE' },
  { name: 'Aeroporto Internacional de Palmas', iata: 'PMW', city: 'Palmas', state: 'TO' },
  { name: 'Aeroporto Internacional de Porto Velho', iata: 'PVH', city: 'Porto Velho', state: 'RO' },
  { name: 'Aeroporto Internacional de Macapá', iata: 'MCP', city: 'Macapá', state: 'AP' },
  { name: 'Aeroporto Internacional de Boa Vista', iata: 'BVB', city: 'Boa Vista', state: 'RR' },
  // ... (adicione todos os outros aeroportos do Brasil conforme necessário) ...
]; 